// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/home/article-card/ArticleCard.vue')['default']
    CardPanel: typeof import('./src/components/card-panel/CardPanel.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    SideNav: typeof import('./src/components/side-nav/SideNav.vue')['default']
    StatisticCard: typeof import('./src/components/statistic-card/StatisticCard.vue')['default']
    SummaryCard: typeof import('./src/components/home/summary-card/SummaryCard.vue')['default']
    TodoCard: typeof import('./src/components/home/todo-card/TodoCard.vue')['default']
    ToolCard: typeof import('./src/components/home/tool-card/ToolCard.vue')['default']
    ToolItem: typeof import('./src/components/tool/ToolItem.vue')['default']
  }
}

export { }
