// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/home/article-card/ArticleCard.vue')['default']
    ArticleListCard: typeof import('./src/components/article/article-list-card/ArticleListCard.vue')['default']
    CardPanel: typeof import('./src/components/card-panel/CardPanel.vue')['default']
    DialogArticleUpload: typeof import('./src/components/article/dialog-article-upload/DialogArticleUpload.vue')['default']
    DialogPictureUpload: typeof import('./src/components/picture/dialog-picture-upload/DialogPictureUpload.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HeaderNav: typeof import('./src/components/header-nav/HeaderNav.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    PictureCard: typeof import('./src/components/picture/picture-card/PictureCard.vue')['default']
    SideNav: typeof import('./src/components/side-nav/SideNav.vue')['default']
    StatisticCard: typeof import('./src/components/statistic-card/StatisticCard.vue')['default']
    SummaryCard: typeof import('./src/components/home/summary-card/SummaryCard.vue')['default']
    TodoCard: typeof import('./src/components/home/todo-card/TodoCard.vue')['default']
    ToolCard: typeof import('./src/components/home/tool-card/ToolCard.vue')['default']
    ToolDate: typeof import('./src/components/tool/ToolDate.vue')['default']
    ToolItem: typeof import('./src/components/tool/ToolItem.vue')['default']
  }
}

export { }
